version: "3.7"

services:
  nginx:
    build:
      context: './nginx'
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - backend
    depends_on:
      - app
    restart: always

  app:
    build:
      context: './app'
    environment:
      - ENV=${ENV}
    networks:
      - backend

networks:
  backend:
