version: "3.7"

services:
  nginx:
    build:
      context: './nginx'
    ports:
      - "80:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
    networks:
      - backend
    depends_on:
      - api
      - app
    restart: always

  db:
    image: postgres:13.1-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartak1
      - POSTGRES_DB=datacademy
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes: 
      - ./api/.database/postgres/data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - ./api/.database/mongo/data:/data/db
    networks:
      - backend

  app:
    build:
      context: './app'
    ports:
      - "3000:3000"
    environment:
      - ENV=${ENV}
    networks:
      - backend

  api:
    build:
      context: './api'
    ports:
      - "3100:3100"
    depends_on: 
      - db
      - mongo
    networks:
      - backend
    environment:
      - ENV=${ENV}
    restart: always

networks:
  backend:

