version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartak1
      - POSTGRES_DB=datacademy
    networks:
      - backend

  app:
    build:
      context: './app'
    ports:
      - "3000:3000"
    environment:
      - ENV=${ENV}
      - DB_SOURCE=postgresql://root:spartak1@localhost:5432/datacademy?sslmode=disable
    networks:
      - backend

  api:
    build:
      context: './api'
    ports:
      - "3100:3100"
    depends_on: 
      - db
    networks:
      - backend
    environment:
      - ENV=${ENV}
    restart: always

networks:
  backend:

