version: "3.7"

services:
  db:
    image: postgres:13.1-alpine
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=spartak1
      - POSTGRES_DB=datalearn
    ports:
      - "5432:5432"
    networks:
      - backend
    volumes: 
      - ./backend/.database/postgres/data:/var/lib/postgresql/data

  mongo:
    image: mongo:4.0
    ports:
      - "27017:27017"
    volumes:
      - ./backend/.database/mongo/data:/data/db
    networks:
      - backend

  frontend:
    build:
      context: './frontend'
    ports:
      - "3000:3000"
    environment:
      - ENV=${ENV}
    networks:
      - backend

  backend:
    build:
      context: './backend'
    ports:
      - "3100:3100"
    depends_on: 
      - db
    networks:
      - backend
    environment:
      - ENV=${ENV}
    restart: always

networks:
  backend:

