version: "3.7"

services:
  app:
    build:
      context: './app'
    ports:
      - "3000:3000"
    environment:
      - ENV=${ENV}
    networks:
      - backend

  api:
    build:
      context: './api'
    ports:
      - "3100:3100"
    networks:
      - backend
    environment:
      - ENV=${ENV}
    restart: always

networks:
  backend:

