apiVersion: apps/v1
kind: Deployment
metadata:
  name: datalearn-api-deployment
  labels:
    app: datalearn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: datalearn-api
  template:
    metadata:
      labels:
        app: datalearn-api
    spec:
      containers:
      - name: datalearn-api
        image: 067789811623.dkr.ecr.us-east-2.amazonaws.com/datalearn-api:latest
        ports:
        - containerPort: 3100