export enum UserAuthActionTypes {
    FETCH_USER_LOGIN_REQUEST = 'FETCH_USER_AUTH_REQUEST',
    FETCH_USER_LOGIN_SUCCESS = 'FETCH_USER_AUTH_SUCCESS',
    FETCH_USER_LOGIN_FAILURE = 'FETCH_USER_AUTH_FAILURE',
    FETCH_USER_LOGOUT_REQUEST = 'FETCH_USER_LOGOUT_REQUEST',
    FETCH_USER_LOGOUT_SUCCESS = 'FETCH_USER_LOGOUT_SUCCESS',
    FETCH_USER_LOGOUT_FAILURE = 'FETCH_USER_LOGOUT_FAILURE'
}

