export enum UserAuthActionTypes {
    FETCH_USER_AUTH_REQUEST = 'FETCH_USER_AUTH_REQUEST',
    FETCH_USER_AUTH_SUCCESS = 'FETCH_USER_AUTH_SUCCESS',
    FETCH_USER_AUTH_FAILURE = 'FETCH_USER_AUTH_FAILURE'
}

