env:
  browser: true
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:react/recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  react/prop-types: off
  @typescript-eslint/no-explicit-any: off
settings:
  react:
    version: 17.0.1
