export enum ModuleActionTypes {
    FETCH_ACTION_CHANGE = 'FETCH_ACTION_CHANGE',
    FETCH_ADD_MODULE_REQUEST = 'FETCH_ADD_MODULE_REQUEST',
    FETCH_ADD_MODULE_SUCCESS = 'FETCH_ADD_MODULE_SUCCESS',
    FETCH_ADD_MODULE_FAILURE = 'FETCH_ADD_MODULE_FAILURE',
}