export { AuthorSection } from './AuthorSection'
export { SyllabusSection } from './SyllabusSection'
export { BeneficiarsSection } from './BeneficiarsSection'
export { TechStackSection } from './TechStackSection'
export { SubscribeSection } from './SubscribeSection'