export enum CourseActionTypes {
    FETCH_ACTION_CHANGE = 'FETCH_ACTION_CHANGE',
    FETCH_ADD_COURSE_REQUEST = 'FETCH_ADD_COURSE_REQUEST',
    FETCH_ADD_COURSE_SUCCESS = 'FETCH_ADD_COURSE_SUCCESS',
    FETCH_ADD_COURSE_FAILURE = 'FETCH_ADD_COURSE_FAILURE',
}