export enum AuthorActionTypes {
    FETCH_ACTION_CHANGE = 'FETCH_ACTION_CHANGE',
    FETCH_ADD_AUTHOR_REQUEST = 'FETCH_ADD_AUTHOR_REQUEST',
    FETCH_ADD_AUTHOR_SUCCESS = 'FETCH_ADD_AUTHOR_SUCCESS',
    FETCH_ADD_AUTHOR_FAILURE = 'FETCH_ADD_AUTHOR_FAILURE',
}